"""initial tables

Revision ID: 480ae09d8665
Revises: 
Create Date: 2025-09-05 15:56:49.281846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480ae09d8665'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tui',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=64), nullable=True),
    sa.Column('CATEGORIA_TUI', sa.String(length=120), nullable=True),
    sa.Column('TIPOS_TUI', sa.String(length=120), nullable=True),
    sa.Column('NOMBRE_TUI', sa.String(length=255), nullable=True),
    sa.Column('ACCESIBILIDAS_SILLA_RUEDAS', sa.String(length=50), nullable=True),
    sa.Column('RESERVA_POSIBLE', sa.String(length=50), nullable=True),
    sa.Column('DIRECCION', sa.String(length=255), nullable=True),
    sa.Column('LATITUD_TUI', sa.Float(), nullable=True),
    sa.Column('LONGITUD_TUI', sa.Float(), nullable=True),
    sa.Column('RATING_TUI', sa.Float(), nullable=True),
    sa.Column('WEBSITE', sa.String(length=255), nullable=True),
    sa.Column('URL', sa.String(length=255), nullable=True),
    sa.Column('TOTAL_VALORACIONES_TUI', sa.Integer(), nullable=True),
    sa.Column('PRECIO', sa.String(length=50), nullable=True),
    sa.Column('ESTADO_NEGOCIO', sa.String(length=50), nullable=True),
    sa.Column('HORARIO', sa.Text(), nullable=True),
    sa.Column('TELEFONO', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tui', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tui_LATITUD_TUI'), ['LATITUD_TUI'], unique=False)
        batch_op.create_index(batch_op.f('ix_tui_LONGITUD_TUI'), ['LONGITUD_TUI'], unique=False)
        batch_op.create_index(batch_op.f('ix_tui_NOMBRE_TUI'), ['NOMBRE_TUI'], unique=False)
        batch_op.create_index(batch_op.f('ix_tui_place_id'), ['place_id'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tui_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tui_id'], ['tui.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tui_id', name='uq_user_tui')
    )
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favoritos_tui_id'), ['tui_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favoritos_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favoritos_user_id'))
        batch_op.drop_index(batch_op.f('ix_favoritos_tui_id'))

    op.drop_table('favoritos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('tui', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tui_place_id'))
        batch_op.drop_index(batch_op.f('ix_tui_NOMBRE_TUI'))
        batch_op.drop_index(batch_op.f('ix_tui_LONGITUD_TUI'))
        batch_op.drop_index(batch_op.f('ix_tui_LATITUD_TUI'))

    op.drop_table('tui')
    # ### end Alembic commands ###
