"""add conversations table

Revision ID: 9bc271a6370d
Revises: d45d0ba78058
Create Date: 2025-09-10 18:48:50.999707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc271a6370d'
down_revision = 'd45d0ba78058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('last_place_ids', sa.JSON(), nullable=True),
    sa.Column('last_user_text', sa.Text(), nullable=True),
    sa.Column('last_assistant_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_id', name='uq_user_conv')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tui', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ACCESIBILIDAD_SILLA_RUEDAS', sa.String(length=50), nullable=True))
        batch_op.drop_column('ACCESIBILIDAS_SILLA_RUEDAS')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tui', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ACCESIBILIDAS_SILLA_RUEDAS', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('ACCESIBILIDAD_SILLA_RUEDAS')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_conversation_id'))

    op.drop_table('conversations')
    # ### end Alembic commands ###
